import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Providers } from './providers';
import { AppHeader } from './(components)/AppHeader';
import { ReactNode } from 'react';
import { getDictionary } from '@/utils/contexts/intl/helpers/getDictionary';
import { getLocale } from '@/utils/contexts/intl/helpers/getLocale';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

interface RootLayoutProps {
  children: ReactNode;
}

const getInitialIntl = async () => {
  const locale = await getLocale();
  const messages = await getDictionary(locale);

  return {
    locale,
    messages
  };
};

const RootLayout = async ({ children }: RootLayoutProps) => {
  const initialIntl = await getInitialIntl();

  return (
    <html lang={initialIntl.locale} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers intl={initialIntl}>
          <AppHeader />
          {children}
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
